### ISSUE TITLE
Alt Click doesn't work

### ISSUE THREAD

**Issue by Kitsunemitsu** [Kitsunemitsu/KirieStation#145]
## Testmerges:

It's the full merge of #128, Suspected to be the autofire port

## Reproduction:
Try alt-clicking a tile and using the tab up top left

**Comment by JohnFulpWillard** [comment]
![bungalow](https://user-images.githubusercontent.com/53777086/117578834-4b633600-b0be-11eb-9f36-c71de0962d44.jpg)

**Comment by Kitsunemitsu** [comment]
It had to do with our Auto-fire code, we're fixing soon

**Comment by EgorDinamit** [comment]
@JohnFulpWillard and you are unironically coding for [DATA EXPUNGED], what about it? :trollface:

**Comment by EgorDinamit** [comment]
@JohnFulpWillard who's laughing now, FulpWillard?
